---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/kubectl"
    build_args:
      - ARCH=amd64
      - KUBERNETES_RELEASE=${DRONE_TAG}
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/kubectl"
      build_args:
        - ARCH=arm64
        - KUBERNETES_RELEASE=${DRONE_TAG}
      tag: "${DRONE_TAG}-arm64"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      password:
        from_secret: docker_password
      repo: "rancher/kubectl"
      build_args:
        - ARCH=arm
        - KUBERNETES_RELEASE=${DRONE_TAG}
      tag: "${DRONE_TAG}-arm"
      username:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
        - refs/tags/*
      event:
        - tag

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/arm
    target: "rancher/kubectl:${DRONE_TAG}"
    template: "rancher/kubectl:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- amd64
- arm64
- arm
