---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: validate-versions
    image: rancher/dapper:v0.6.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
    - dapper check-versions.sh
    when:
      instance:
        - drone-pr.rancher.io
      event:
        - pull_request

  - name: docker-build-publish
    image: rancher/dapper:v0.6.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
    - dapper image-build-and-push.sh
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
      event:
        - push

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
  - name: docker-build-publish
    image: rancher/dapper:v0.6.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
    - dapper image-build-and-push.sh
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
      event:
        - push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
name: s390x

platform:
  os: linux
  arch: amd64

node:
  arch: s390x

steps:
  - name: docker-build-publish
    image: rancher/dapper:v0.6.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
    - dapper image-build-and-push.sh
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
      DOCKER_USERNAME:
        from_secret: docker_username
    when:
      instance:
        - drone-publish.rancher.io
      ref:
        - refs/head/master
      event:
        - push

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---

kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: rancher/dapper:v0.6.0
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
  - dapper manifest-create-and-push.sh
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    instance:
      - drone-publish.rancher.io
    ref:
      - refs/head/master
    event:
      - push

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

depends_on:
- amd64
- arm64
- s390x
