name: Validate PR
on:
  workflow_call:
  pull_request:
  pull_request_review:
    types: [ submitted ]

env:
  IMAGE_REPO: ${{ github.repository }}

jobs:
  validate-versions:
    name: "Check kubectl release versions"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - run: scripts/check-versions.sh
      - name: Find newest kubectl version
        run: |
          newest=$(head -n 1 versions.txt)
          echo "KUBECTL_VERSION=$newest" >> $GITHUB_ENV
      - name: Build image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        id: build-image
        with:
          context: .
          file: package/Dockerfile
          platforms: "linux/amd64"
          push: false
          load: true
          tags: ${{ env.IMAGE_REPO }}:${{ env.KUBECTL_VERSION }}-pr
          build-args: |
            KUBERNETES_RELEASE=${{ env.KUBECTL_VERSION }}
      - name: Unit test image
        run: scripts/unit-test-image.sh ${{ env.KUBECTL_VERSION }}-pr
        env:
          REPO: ${{ env.IMAGE_REPO }}